# Generated by Django 5.0.2 on 2024-03-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('talle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('talle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Puma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('talle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Remeras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('talle', models.CharField(max_length=50)),
            ],
        ),
    ]
